# Tutorial: Multi-dimensional Arrays (Solution)

Use list comprehension to create a list called `gridList` containing 6 sublists, each containing 6 zeros. Print `gridList` to the screen.

In [15]:
gridList = [[0 for _ in range(6)] for _ in range(6)]

print(gridList)

[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]


Convert `gridList` to a `numpy` array called `gridArray` and print it to the screen.

In [16]:
import numpy as np

gridArray = np.array(gridList)

print(gridArray)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


Change the four central values of the grid array to ones instead of zeros using index slicing and print the array to the screen again.

In [17]:
gridArray[2:4, 2:4] = 1

print(gridArray)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


Change the top right value in the array to a `5` and print it to the screen.

In [18]:
gridArray[0, -1] = 5

print(gridArray)

[[0 0 0 0 0 5]
 [0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


Transpose the array and print it to the screen.

In [19]:
print(gridArray.T)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]
 [5 0 0 0 0 0]]
